# config/meta.yml
meta_product_name: "Product Name"
meta_title: "Propulse - Orientation et Avenir"
meta_description: "Aide les lycéens à s’orienter et à choisir leur avenir professionnel sereinement."
meta_image: 'default-meta-image.jpg' # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
